import type { Connection, PublicKey, VersionedTransaction, Transaction } from "@solana/web3.js";

export type RiskLevel = "safe" | "caution" | "danger";

export type Severity = "low" | "medium" | "high";

export type FlagId =
  | "KNOWN_DRAINER_PROGRAM"
  | "FULL_TOKEN_APPROVAL"
  | "UNKNOWN_PROGRAM"
  | "MULTI_INSTRUCTION_COMPLEXITY"
  | "SIMULATION_SPOOF"
  | "UNUSUAL_FEE"
  // Schema-only; runtime detection ships with the browser extension:
  | "TOCTOU_PATTERN";

export interface TxRiskFlag {
  id: FlagId;
  severity: Severity;
  label: string;
  description: string;
  /** Optional structured evidence — pubkeys, instruction indices, decoded values. */
  evidence?: Record<string, unknown>;
}

export interface DecodedInstruction {
  /** Index in the transaction's top-level instruction list. */
  index: number;
  /** Program address, base58. */
  programId: string;
  /** Human-readable program name if known, else "Unknown program". */
  programName: string;
  /** One-line plain-English summary of what the instruction does. */
  summary: string;
  /** Best-effort decoded type tag, e.g. "spl-token:Approve". Optional. */
  type?: string;
  /** Base58 account addresses involved. */
  accounts: string[];
}

export interface ParsedTransaction {
  /** Transaction version: "legacy" or 0 (v0). */
  version: "legacy" | 0;
  /** All account keys, with ALT-resolved keys merged in for v0 transactions. */
  accountKeys: string[];
  /** Top-level instructions, with program ids resolved to base58. */
  instructions: ParsedInstruction[];
  /** Signers (base58). The first signer is conventionally the fee payer. */
  signers: string[];
  /** Fee payer (base58). */
  feePayer: string;
  /** Whether ALT resolution was attempted and succeeded for all referenced tables. */
  altResolved: boolean;
  /** Recent blockhash if present (legacy + v0). */
  recentBlockhash?: string;
}

export interface ParsedInstruction {
  index: number;
  programId: string;
  /** Account addresses (base58) referenced by this instruction. */
  accounts: string[];
  /** Raw instruction data as Uint8Array — already validated as bytes. */
  data: Uint8Array;
}

export interface AnalyzeOptions {
  /** Base64-encoded serialized transaction. */
  transaction: string | VersionedTransaction | Transaction;
  /** Solana RPC connection. */
  connection: Connection;
  /** Optional signer pubkey for context-aware checks. */
  publicKey?: PublicKey;
  /** "fast" = rules only (no LLM, no simulation); "full" = rules + simulation + AI explainer. */
  mode?: "fast" | "full";
  /** Optional override for which model to use in full mode. */
  model?: string;
}

export interface SimulationDelta {
  /** Token mint → net balance change for the signer. Negative = outflow. */
  tokenDeltas: Record<string, bigint>;
  /** Net SOL (lamport) change for the signer. */
  solDelta: bigint;
  /** Whether simulation succeeded. */
  ok: boolean;
  /** Simulation error message if `ok=false`. */
  error?: string;
}

export interface TxRiskResult {
  /** Overall verdict — derived deterministically from flags + scorer. */
  riskLevel: RiskLevel;
  /** 0–100, higher = more risk. */
  score: number;
  /** Detected risk flags. */
  flags: TxRiskFlag[];
  /** Plain-English LLM translation. Empty string in fast mode. */
  explanation: string;
  /** Action recommendation, locked to riskLevel. */
  recommendation: "Safe to sign" | "Proceed with caution" | "Do not sign";
  /** Bullet list of what the transaction does, generated by the LLM in full mode. */
  whatThisDoes: string[];
  /** Decoded instructions surfaced to the UI. */
  decodedInstructions: DecodedInstruction[];
  /** Optional raw simulation summary for the developer/raw view. */
  simulation?: SimulationDelta;
  /** ISO timestamp. */
  analyzedAt: string;
  /** Mode used for this analysis. */
  mode: "fast" | "full";
}
