[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

# Live devnet deployment.
# Explorer: https://explorer.solana.com/address/Dt6ccUKifBKegcxKGvgiHfyCDrJFeRwMmhvi7eCbFVS7?cluster=devnet
[programs.localnet]
txguardian_registry = "Dt6ccUKifBKegcxKGvgiHfyCDrJFeRwMmhvi7eCbFVS7"

[programs.devnet]
txguardian_registry = "Dt6ccUKifBKegcxKGvgiHfyCDrJFeRwMmhvi7eCbFVS7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec mocha -r ts-node/register -t 1000000 tests/**/*.ts"
