import * as anchor from "@coral-xyz/anchor";
import type { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
} from "@solana/web3.js";
import { expect } from "chai";

/**
 * Anchor tests for the TxGuardian risk-attestation registry.
 *
 * Run with: `anchor test`
 *
 * The IDL types under target/types/ are generated by `anchor build`. We
 * cast `program` to `Program<any>` so this file remains parseable and
 * editor-tractable before the first build.
 */
describe("txguardian_registry", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.TxguardianRegistry as Program<any>;
  const wallet = provider.wallet as anchor.Wallet;
  const admin = wallet.payer;

  const [registryPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("registry")],
    program.programId,
  );

  function attestationPda(targetProgram: PublicKey): PublicKey {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from("attestation"), targetProgram.toBuffer()],
      program.programId,
    );
    return pda;
  }

  function reasonBytes(text: string): number[] {
    const buf = Buffer.alloc(64);
    buf.write(text, "utf-8");
    return Array.from(buf);
  }

  async function fundedKeypair(lamports = LAMPORTS_PER_SOL): Promise<Keypair> {
    const kp = Keypair.generate();
    const sig = await provider.connection.requestAirdrop(
      kp.publicKey,
      lamports,
    );
    await provider.connection.confirmTransaction(sig, "confirmed");
    return kp;
  }

  it("initializes the registry", async () => {
    await program.methods
      .initialize(admin.publicKey)
      .accounts({
        registry: registryPda,
        payer: admin.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const registry = await program.account.registry.fetch(registryPda);
    expect(registry.admin.toBase58()).to.equal(admin.publicKey.toBase58());
    expect(registry.submissionCount.toNumber()).to.equal(0);
    expect(registry.confirmedCount.toNumber()).to.equal(0);
  });

  it("rejects re-initialization", async () => {
    let threw = false;
    try {
      await program.methods
        .initialize(admin.publicKey)
        .accounts({
          registry: registryPda,
          payer: admin.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
    } catch (err) {
      threw = true;
      expect(String(err)).to.match(/already in use|0x0/i);
    }
    expect(threw, "expected re-init to throw").to.equal(true);
  });

  it("submits an attestation in pending state", async () => {
    const target = Keypair.generate().publicKey;
    const attPda = attestationPda(target);

    await program.methods
      .submit(target, 3, reasonBytes("known drainer pattern"))
      .accounts({
        registry: registryPda,
        attestation: attPda,
        submitter: admin.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const att = await program.account.attestation.fetch(attPda);
    expect(att.targetProgram.toBase58()).to.equal(target.toBase58());
    expect(att.severity).to.equal(3);
    expect(att.status).to.equal(0); // STATUS_PENDING
    expect(att.submitter.toBase58()).to.equal(admin.publicKey.toBase58());

    const registry = await program.account.registry.fetch(registryPda);
    expect(registry.submissionCount.toNumber()).to.be.greaterThan(0);
  });

  it("rejects submit with invalid severity", async () => {
    const target = Keypair.generate().publicKey;
    const attPda = attestationPda(target);

    let threw = false;
    try {
      await program.methods
        .submit(target, 7, reasonBytes("invalid"))
        .accounts({
          registry: registryPda,
          attestation: attPda,
          submitter: admin.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
    } catch (err) {
      threw = true;
      expect(String(err)).to.match(/InvalidSeverity/i);
    }
    expect(threw, "expected invalid severity to throw").to.equal(true);
  });

  it("rejects duplicate submission for the same program", async () => {
    const target = Keypair.generate().publicKey;
    const attPda = attestationPda(target);

    await program.methods
      .submit(target, 2, reasonBytes("first"))
      .accounts({
        registry: registryPda,
        attestation: attPda,
        submitter: admin.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    let threw = false;
    try {
      await program.methods
        .submit(target, 2, reasonBytes("second"))
        .accounts({
          registry: registryPda,
          attestation: attPda,
          submitter: admin.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
    } catch (err) {
      threw = true;
      expect(String(err)).to.match(/already in use|0x0/i);
    }
    expect(threw, "expected duplicate submit to throw").to.equal(true);
  });

  it("rejects attest from a non-admin signer", async () => {
    const target = Keypair.generate().publicKey;
    const attPda = attestationPda(target);
    const stranger = await fundedKeypair();

    await program.methods
      .submit(target, 3, reasonBytes("for non-admin attest"))
      .accounts({
        registry: registryPda,
        attestation: attPda,
        submitter: admin.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    let threw = false;
    try {
      await program.methods
        .attest(target)
        .accounts({
          registry: registryPda,
          attestation: attPda,
          admin: stranger.publicKey,
        })
        .signers([stranger])
        .rpc();
    } catch (err) {
      threw = true;
      expect(String(err)).to.match(/Unauthorized|has_one|ConstraintHasOne/i);
    }
    expect(threw, "expected non-admin attest to throw").to.equal(true);
  });

  it("attests a pending attestation as admin", async () => {
    const target = Keypair.generate().publicKey;
    const attPda = attestationPda(target);

    await program.methods
      .submit(target, 3, reasonBytes("for confirm"))
      .accounts({
        registry: registryPda,
        attestation: attPda,
        submitter: admin.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const before = await program.account.registry.fetch(registryPda);

    await program.methods
      .attest(target)
      .accounts({
        registry: registryPda,
        attestation: attPda,
        admin: admin.publicKey,
      })
      .rpc();

    const att = await program.account.attestation.fetch(attPda);
    expect(att.status).to.equal(1); // STATUS_CONFIRMED
    expect(att.attestedBy.toBase58()).to.equal(admin.publicKey.toBase58());

    const after = await program.account.registry.fetch(registryPda);
    expect(after.confirmedCount.toNumber()).to.equal(
      before.confirmedCount.toNumber() + 1,
    );
  });

  it("revokes a confirmed attestation and decrements confirmed_count", async () => {
    const target = Keypair.generate().publicKey;
    const attPda = attestationPda(target);

    await program.methods
      .submit(target, 3, reasonBytes("for revoke"))
      .accounts({
        registry: registryPda,
        attestation: attPda,
        submitter: admin.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    await program.methods
      .attest(target)
      .accounts({
        registry: registryPda,
        attestation: attPda,
        admin: admin.publicKey,
      })
      .rpc();

    const before = await program.account.registry.fetch(registryPda);

    await program.methods
      .revoke(target)
      .accounts({
        registry: registryPda,
        attestation: attPda,
        admin: admin.publicKey,
      })
      .rpc();

    const att = await program.account.attestation.fetch(attPda);
    expect(att.status).to.equal(2); // STATUS_REVOKED

    const after = await program.account.registry.fetch(registryPda);
    expect(after.confirmedCount.toNumber()).to.equal(
      before.confirmedCount.toNumber() - 1,
    );
  });

  it("rotates the admin and locks out the old admin", async () => {
    const newAdmin = await fundedKeypair();

    await program.methods
      .updateAdmin(newAdmin.publicKey)
      .accounts({
        registry: registryPda,
        admin: admin.publicKey,
      })
      .rpc();

    const reg = await program.account.registry.fetch(registryPda);
    expect(reg.admin.toBase58()).to.equal(newAdmin.publicKey.toBase58());

    // Old admin should now be locked out.
    const target = Keypair.generate().publicKey;
    const attPda = attestationPda(target);
    await program.methods
      .submit(target, 1, reasonBytes("post-rotation"))
      .accounts({
        registry: registryPda,
        attestation: attPda,
        submitter: admin.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    let threw = false;
    try {
      await program.methods
        .attest(target)
        .accounts({
          registry: registryPda,
          attestation: attPda,
          admin: admin.publicKey, // old admin
        })
        .rpc();
    } catch (err) {
      threw = true;
      expect(String(err)).to.match(/Unauthorized|has_one|ConstraintHasOne/i);
    }
    expect(threw, "expected old admin to be rejected").to.equal(true);

    // Restore: new admin rotates back to old (defensive — keeps test idempotent).
    await program.methods
      .updateAdmin(admin.publicKey)
      .accounts({
        registry: registryPda,
        admin: newAdmin.publicKey,
      })
      .signers([newAdmin])
      .rpc();
  });
});
