#!/usr/bin/env tsx
/**
 * Seed the on-chain TxGuardian registry.
 *
 * Initializes the singleton Registry PDA (idempotent — skips if already
 * initialized) and submits + attests a handful of programs so the /registry
 * page and /scan have data to display.
 *
 * Run from the repo root after `anchor build`:
 *
 *   pnpm seed-registry
 *
 * Requirements:
 *   - target/idl/txguardian_registry.json exists (generated by anchor build)
 *   - ~/.config/solana/id.json has devnet SOL (~0.05 SOL needed for 4 entries)
 *   - Solana CLI configured for devnet
 */

import * as anchor from "@coral-xyz/anchor";
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  clusterApiUrl,
} from "@solana/web3.js";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

const PROGRAM_ID = new PublicKey(
  "Dt6ccUKifBKegcxKGvgiHfyCDrJFeRwMmhvi7eCbFVS7",
);
const IDL_PATH = path.resolve(
  process.cwd(),
  "target/idl/txguardian_registry.json",
);

interface Sample {
  /** Seed byte for Keypair.fromSeed (deterministic mock pubkey). */
  seed: number;
  severity: 1 | 2 | 3;
  reason: string;
  /** Skip the attest step? Surfaces a "pending" entry on the registry table. */
  pendingOnly?: boolean;
  /** Revoke after attesting? Surfaces the "revoked" status. */
  revoke?: boolean;
  /** Notes for the operator (printed during seeding). */
  note?: string;
}

const SAMPLES: Sample[] = [
  // Matches the DANGER sample's unknown program (apps/web/lib/fixtures.ts seed=9).
  // After seeding, scanning the DANGER sample triggers an on-chain match in
  // addition to the existing static UNKNOWN_PROGRAM flag.
  {
    seed: 9,
    severity: 3,
    reason: "Pattern matches known wallet drainer signature",
    note: "Linked to /scan DANGER sample",
  },
  // Matches the CAUTION sample's unknown program (seed=5).
  {
    seed: 5,
    severity: 2,
    reason: "Unverified contract used by suspicious aggregator",
    note: "Linked to /scan CAUTION sample",
  },
  // Pending — surfaces the pending lifecycle on the /registry table.
  {
    seed: 21,
    severity: 3,
    reason: "Reported by community; pending admin review",
    pendingOnly: true,
    note: "Pending lifecycle entry",
  },
  // Revoked — false-positive cleanup.
  {
    seed: 22,
    severity: 1,
    reason: "Initially flagged, cleared after review",
    revoke: true,
    note: "Revoked lifecycle entry",
  },
];

function deterministicKeypair(seedByte: number): Keypair {
  return Keypair.fromSeed(new Uint8Array(32).fill(seedByte));
}

function reasonBytes(text: string): number[] {
  const buf = Buffer.alloc(64);
  buf.write(text, "utf-8");
  return Array.from(buf);
}

function loadWallet(): Keypair {
  const p = path.join(os.homedir(), ".config", "solana", "id.json");
  if (!fs.existsSync(p)) {
    throw new Error(
      `No keypair at ${p}. Run "solana-keygen new" or set CLI to use a different wallet.`,
    );
  }
  const raw = JSON.parse(fs.readFileSync(p, "utf8"));
  return Keypair.fromSecretKey(Uint8Array.from(raw));
}

function makeWallet(kp: Keypair): anchor.Wallet {
  // Minimal Wallet shape for AnchorProvider.
  return {
    publicKey: kp.publicKey,
    payer: kp,
    signTransaction: async <
      T extends anchor.web3.Transaction | anchor.web3.VersionedTransaction,
    >(
      tx: T,
    ): Promise<T> => {
      if ("partialSign" in tx) {
        tx.partialSign(kp);
      } else {
        (tx as anchor.web3.VersionedTransaction).sign([kp]);
      }
      return tx;
    },
    signAllTransactions: async <
      T extends anchor.web3.Transaction | anchor.web3.VersionedTransaction,
    >(
      txs: T[],
    ): Promise<T[]> => {
      for (const tx of txs) {
        if ("partialSign" in tx) {
          tx.partialSign(kp);
        } else {
          (tx as anchor.web3.VersionedTransaction).sign([kp]);
        }
      }
      return txs;
    },
  } as anchor.Wallet;
}

function statusName(byte: number): string {
  return byte === 0 ? "pending" : byte === 1 ? "confirmed" : "revoked";
}

async function main() {
  if (!fs.existsSync(IDL_PATH)) {
    console.error(`Could not find IDL at ${IDL_PATH}`);
    console.error("Run `anchor build` first.");
    process.exit(1);
  }

  const idl = JSON.parse(fs.readFileSync(IDL_PATH, "utf8"));
  const wallet = makeWallet(loadWallet());
  const rpcUrl = process.env.RPC_URL ?? clusterApiUrl("devnet");
  const connection = new Connection(rpcUrl, "confirmed");
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const program = new anchor.Program(idl as anchor.Idl, provider) as any;

  const [registryPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("registry")],
    PROGRAM_ID,
  );

  console.log("Wallet:        ", wallet.publicKey.toBase58());
  console.log("RPC:           ", rpcUrl);
  console.log("Program:       ", PROGRAM_ID.toBase58());
  console.log("Registry PDA:  ", registryPda.toBase58());
  console.log();

  // 1. Initialize (idempotent)
  let alreadyInitialized = false;
  try {
    const reg = await program.account.registry.fetch(registryPda);
    alreadyInitialized = true;
    console.log("Registry already initialized:");
    console.log("  admin:           ", reg.admin.toBase58());
    console.log("  submissionCount: ", reg.submissionCount.toString());
    console.log("  confirmedCount:  ", reg.confirmedCount.toString());
  } catch {
    console.log("Initializing registry...");
    await program.methods
      .initialize(wallet.publicKey)
      .accounts({
        registry: registryPda,
        payer: wallet.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    console.log("✓ Registry initialized");
  }
  console.log();

  // 2. Submit + attest each sample
  for (const sample of SAMPLES) {
    const target = deterministicKeypair(sample.seed).publicKey;
    const [attPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("attestation"), target.toBuffer()],
      PROGRAM_ID,
    );

    console.log(
      `Sample seed=${sample.seed} severity=${sample.severity}` +
        (sample.note ? `  [${sample.note}]` : ""),
    );
    console.log(`  target: ${target.toBase58()}`);

    let exists = false;
    let existing: { status: number } | null = null;
    try {
      existing = await program.account.attestation.fetch(attPda);
      exists = true;
    } catch {
      /* not yet submitted */
    }

    if (!exists) {
      console.log("  submitting...");
      await program.methods
        .submit(target, sample.severity, reasonBytes(sample.reason))
        .accounts({
          registry: registryPda,
          attestation: attPda,
          submitter: wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
    } else if (existing) {
      console.log(`  already submitted (status=${statusName(existing.status)})`);
    }

    if (sample.pendingOnly) {
      console.log("  ✓ left as pending");
      console.log();
      continue;
    }

    if (!existing || existing.status === 0) {
      console.log("  attesting...");
      try {
        await program.methods
          .attest(target)
          .accounts({
            registry: registryPda,
            attestation: attPda,
            admin: wallet.publicKey,
          })
          .rpc();
      } catch (err) {
        if (String(err).includes("AlreadyConfirmed")) {
          console.log("  (already confirmed)");
        } else {
          throw err;
        }
      }
    }

    if (sample.revoke) {
      console.log("  revoking...");
      try {
        await program.methods
          .revoke(target)
          .accounts({
            registry: registryPda,
            attestation: attPda,
            admin: wallet.publicKey,
          })
          .rpc();
      } catch (err) {
        if (String(err).includes("AlreadyRevoked")) {
          console.log("  (already revoked)");
        } else {
          throw err;
        }
      }
    }

    console.log("  ✓");
    console.log();
  }

  // 3. Print final state summary
  const reg = await program.account.registry.fetch(registryPda);
  console.log("---");
  console.log("Final registry state:");
  console.log("  submissionCount: ", reg.submissionCount.toString());
  console.log("  confirmedCount:  ", reg.confirmedCount.toString());
  console.log();
  console.log(
    `Open https://explorer.solana.com/address/${PROGRAM_ID.toBase58()}?cluster=devnet`,
  );
  console.log("to see the program. Refresh /registry on the web app.");
  if (!alreadyInitialized) {
    console.log("\nNote: SDK uses a 60s in-memory cache, so /scan may take up to");
    console.log("a minute to pick up new on-chain entries.");
  }
}

main().catch((err) => {
  console.error("\nERROR:", err);
  process.exit(1);
});
